"""Добавление колонки в таблицу laptops

Revision ID: 1b27435df02a
Revises: a850ab0af5bc
Create Date: 2024-03-17 20:30:14.718146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b27435df02a'
down_revision: Union[str, None] = 'a850ab0af5bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('laptops', sa.Column('cpu', sa.String(), nullable=True))
    op.alter_column('laptops', 'cpu', type_=sa.String())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('laptops', 'cpu')
    op.create_table('workers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='workers_pkey')
    )
    # ### end Alembic commands ###
