"""Таблица all_products/Удаление таблиц определяющих категории

Revision ID: 44c1e224af15
Revises: b5508a9ab11e
Create Date: 2024-02-29 18:30:20.697086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44c1e224af15'
down_revision: Union[str, None] = 'b5508a9ab11e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("all_products",
        sa.Column("id", sa.Integer, primary_key=True),
                 sa.Column("name", sa.String, nullable=False),
                 sa.Column("price", sa.Integer, nullable=False,
                           info={"check": "price >= 0"}),
                 sa.Column("category", sa.String, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
