"""Таблица laptops

Revision ID: 483eac6d456b
Revises: b5fe72abd653
Create Date: 2024-02-25 18:29:43.854687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '483eac6d456b'
down_revision: Union[str, None] = 'b5fe72abd653'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("laptops",
                sa.Column("id", sa.Integer, primary_key=True),
                 sa.Column("name", sa.String, nullable=False),
                 sa.Column("price", sa.Integer, nullable=False),
                 sa.Column("cpu", sa.String, nullable=True),
                 sa.Column("videocard", sa.String, nullable=True),
                 sa.Column("ram", sa.Integer, nullable=True),
                 sa.Column("storage", sa.Integer, nullable=True),
                 sa.Column("display", sa.String, nullable=True),
                 sa.Column("description", sa.String, nullable=True),
                 sa.Column("category_id", sa.Integer, nullable=True),
                 sa.ForeignKeyConstraint(["category_id"], ["categories.id"]))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("laptops")
    # ### end Alembic commands ###
