"""К таблицам orders, sells добавлены столбцы contacts

Revision ID: 7b1fcbda3478
Revises: 8aa5b552ea68
Create Date: 2024-02-14 16:50:51.709448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b1fcbda3478'
down_revision: Union[str, None] = '8aa5b552ea68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_table', sa.Column('contact', sa.String(), nullable=True))
    op.add_column('sell_table', sa.Column('contact', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sell_table', 'contact')
    op.drop_column('order_table', 'contact')
    # ### end Alembic commands ###
