"""Удаление столбца price из таблица order_table

Revision ID: 8aa5b552ea68
Revises: c782e3621e54
Create Date: 2024-02-14 13:54:53.030256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8aa5b552ea68'
down_revision: Union[str, None] = 'c782e3621e54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_table', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_table', sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
