"""Меняем колонку posting_date в таблицах sells/orders

Revision ID: a850ab0af5bc
Revises: 288d9189b162
Create Date: 2024-03-03 19:10:55.302203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a850ab0af5bc'
down_revision: Union[str, None] = '288d9189b162'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sales')
    op.drop_table('my_table')

    op.alter_column('orders_table', 'name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)

    op.alter_column('orders_table', 'contact',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)

    op.alter_column('orders_table', 'posting_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    op.alter_column('sells_table', 'name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)

    op.alter_column('sells_table', 'price',
               existing_type=sa.INTEGER(),
               nullable=False)

    op.alter_column('sells_table', 'contact',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)

    op.alter_column('sells_table', 'posting_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
