"""Таблица tvs

Revision ID: b5508a9ab11e
Revises: d1925b9e5a79
Create Date: 2024-02-25 18:36:23.962451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5508a9ab11e'
down_revision: Union[str, None] = 'd1925b9e5a79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("tvs",
                sa.Column("id", sa.Integer, primary_key=True),
                 sa.Column("name", sa.String, nullable=False),
                 sa.Column("price", sa.Integer, nullable=False),
                 sa.Column("display", sa.String, nullable=True),
                 sa.Column("qled", sa.String, nullable=True),
                 sa.Column("smart_tv", sa.String, nullable=True),
                 sa.Column("hdr", sa.String, nullable=True),
                 sa.Column("description", sa.String, nullable=True),
                 sa.Column("category_id", sa.Integer, nullable=True),
                 sa.ForeignKeyConstraint(["category_id"], ["categories.id"]))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tvs")
    # ### end Alembic commands ###
