"""Таблица cosmetics

Revision ID: b5fe72abd653
Revises: d538c0ff097f
Create Date: 2024-02-25 18:26:43.992852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5fe72abd653'
down_revision: Union[str, None] = 'd538c0ff097f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("cosmetics",
                sa.Column("id", sa.Integer, primary_key=True),
                 sa.Column("name", sa.String, nullable=False),
                 sa.Column("price", sa.Integer, nullable=False),
                 sa.Column("description", sa.String, nullable=True),
                 sa.Column("category_id", sa.Integer, nullable=True),
                 sa.ForeignKeyConstraint(["category_id"], ["categories.id"]))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("cosmetics")
    # ### end Alembic commands ###
