"""Таблица Photos

Revision ID: baa85187f363
Revises: 7e5da3cb2382
Create Date: 2024-03-19 19:11:14.491152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baa85187f363'
down_revision: Union[str, None] = '7e5da3cb2382'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("photos",
                    sa.Column("id", sa.INTEGER(), primary_key=True),
                             sa.Column("file_id", sa.String()),
                             sa.Column("product_id", sa.INTEGER(), sa.ForeignKey(
                                 column="all_products.id", ondelete="CASCADE"
                             )))

    op.drop_table("workers")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
