"""Добавили временные колонки в таблицы Sells, Orders

Revision ID: cf12dfed9696
Revises: 07925e4e9c77
Create Date: 2024-02-21 19:08:52.145622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf12dfed9696'
down_revision: Union[str, None] = '07925e4e9c77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_table', sa.Column('posting_date', sa.DateTime(), server_default=sa.func.current_timestamp()))

    op.add_column('sell_table', sa.Column('posting_date', sa.DateTime(), server_default=sa.func.current_timestamp()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sell_table', 'posting_date')
    op.drop_column('order_table', 'posting_date')

    # ### end Alembic commands ###
