"""Таблица children_goods

Revision ID: d538c0ff097f
Revises: 60ee95f1dc94
Create Date: 2024-02-25 18:23:50.205276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd538c0ff097f'
down_revision: Union[str, None] = '60ee95f1dc94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("children_goods",
                sa.Column("id", sa.Integer, primary_key=True),
                 sa.Column("name", sa.String, nullable=False),
                 sa.Column("price", sa.Integer, nullable=False),
                 sa.Column("description", sa.String, nullable=True),
                 sa.Column("category_id", sa.Integer, nullable=True),
                 sa.ForeignKeyConstraint(["category_id"], ["categories.id"]))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("children_goods")
    # ### end Alembic commands ###
