"""Установили значение по умолчанию в таблице phones, в колонке category_id

Revision ID: e399e808472b
Revises: f95c3d015d3a
Create Date: 2024-02-25 15:18:07.216997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e399e808472b'
down_revision: Union[str, None] = 'f95c3d015d3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('phones', "category_id", server_default="1")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("phones", "category_id", server_default=None)
    # ### end Alembic commands ###
