"""Отредактировали таблицу смартфоны

Revision ID: f95c3d015d3a
Revises: 9f7b35d54e5e
Create Date: 2024-02-25 01:04:37.455041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f95c3d015d3a'
down_revision: Union[str, None] = '9f7b35d54e5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("phones", sa.Column("cpu", sa.String))
    op.add_column("phones", sa.Column("ram", sa.Integer))
    op.add_column("phones", sa.Column("storage", sa.Integer))
    op.add_column("phones", sa.Column("display", sa.String))
    op.add_column("phones", sa.Column("battery", sa.String))
    op.add_column("phones", sa.Column("sim", sa.Integer))
    op.add_column("phones", sa.Column("camera", sa.String))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(table_name="phones", column_name="cpu")
    op.drop_column(table_name="phones", column_name="ram")
    op.drop_column(table_name="phones", column_name="storage")
    op.drop_column(table_name="phones", column_name="display")
    op.drop_column(table_name="phones", column_name="battery")
    op.drop_column(table_name="phones", column_name="sim")
    op.drop_column(table_name="phones", column_name="camera")
    # ### end Alembic commands ###
